import "virtual:svg-icons-register";
import "../scss/style.scss";
import benefitsSlider from "./benefits";
import intro from "./intro";
import header from "./header";
import loader from "./loader";
import catalog from "./catalog";
import modals from "./modals";
import fileUpload from "./fileUpload";
import selects from "./selects";
import forms from "./forms";
import catalogDetail from "./catalogDetail";
import tabs from "./tabs";
import eventsSelects from "./eventsSelects";
import eventsDatepicker from "./eventsDatepicker";
import eventDetail from "./eventDetail";
import collabIntroSlider from "./collabIntroSlider";
import awardsSlider from "./awardsSlider";
import childClubIntroSlider from "./childClubIntroSlider";
import nowOnScreenSlider from "./nowOnScreenSlider";
import cinemaAbout from "./cinemaAbout";
import cinemaIntroSlider from "./cinemaIntroSlider";
import modalCalendar from "./modalCalendar";
import showMap from "./shopMap";
import mapDetail from "./mapDetail";
import homeCatalogAnimation from "./homeCatalogAnimation";

document.addEventListener("DOMContentLoaded", () => {
  benefitsSlider();
  intro();
  header();
  loader();
  catalog();
  selects();
  fileUpload();
  modals();
  tabs();
  forms();
  catalogDetail();
  eventDetail();
  eventsSelects();
  eventsDatepicker();
  collabIntroSlider();
  awardsSlider();
  childClubIntroSlider();
  nowOnScreenSlider();
  cinemaAbout();
  cinemaIntroSlider();
  modalCalendar();
  showMap();
  mapDetail();
  homeCatalogAnimation();
});

window.addEventListener("load", () => {
  document.body.classList.add("loaded");
});
